moofPl:
  enabled: true
  blockedCmds:
    - pl
    - plugins
    - ?
  infoCmds:
    - /set
    - /replace
    - /sphere
    - /undo
    - sudo
  canOp:
    - moofmonkey
  jail:
    x: 0
    y: -6
    z: 0