moofPl:
  enabled: true
  blockedCmds:
  - pl
  - plugins
  - null: null
  infoCmds:
  - /set
  - /replace
  - /sphere
  - /undo
  - sudo
  canOp:
  - moofMonkey
  - kentavo
  - manix
  - kuja
  jails:
    list:
      - jail
    jail:
      x: 0
      y: 0
      z: 0
      name: Main jail
      world: world
  enderchests: {}
